concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "CIPL-LPT-1626"
  url = "https://gitlab.com/"
  id = 29688277
  token = "nHQDNQsTUyfJDuZK-i1g"
  token_obtained_at = 2023-11-22T06:31:42Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "powershell"
  [runners.cache]
    MaxUploadedArchiveSize = 0

# listen_address
Defines an address (<host>:<port>) the Prometheus metrics HTTP server should listen on.

